### ISSUE TITLE
Ignore

### ISSUE THREAD

**Issue by josephnarai** [Brondahl/EnumStringValues#7]
Close

**Comment by Brondahl** [comment]
Original comment question from @josephnarai:

> Hi,
> I'm building an app that I need to sign with an EV Certificate.
> I'm using your great package... but I've just added the signing and I now get:
> `Warning CS8002 Referenced assembly 'EnumStringValues, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.`
> Is this something that can be fixed? Or is there a workaround you know of?

**Comment by Brondahl** [comment]
@josephnarai given that you've closed this, is it safe to assume that you figured out a work-around?

If so great :) but even then if there's something simple I can do to make consumer's life easier, so that it JustWorks, rather than needing some faffy work-around, then I'm pretty open to sorting it out?

**Comment by Brondahl** [comment]
I've never worked with signed stuff, so it's not something I'm familiar with.
Did you find guides to what would be necessary for me to change, in your investigation?

**Comment by josephnarai** [comment]
I've not either. The reason I closed the issue is that as a test I removed all your code and still had an error, so I'm not sure yet what the issue actually is, nor how to fix it.

**Comment by Brondahl** [comment]
Did you remove the project references/dependencies on ESV too? Or just the in-code references to it?
Given that the error message refers to ESV specifically, it seems likely that it *is* relevant?

**Comment by josephnarai** [comment]
It certainly could be. I stopped investigating it specifically when i realized I still had issues... I'll try putting it back once I get my mainapo to sign without error. I'm new to this too.

Joseph Narai • Zenso
________________________________
